#include <esp_now.h>
#include <WiFi.h>

// Define the MAC address of the receiver
uint8_t receiverMAC[] = {0x, 0x, 0x, 0x, 0x, 0x};

typedef struct {
  int counter;
} Message;

Message myData;
esp_now_peer_info_t peerInfo;

void onDataSent(const wifi_tx_info_t *tx_info, esp_now_send_status_t status) {
  Serial.print("Send status: ");
  Serial.println(status == ESP_NOW_SEND_SUCCESS ? "Success" : "Fail");
}

void setup() {
  Serial.begin(115200);
  WiFi.mode(WIFI_STA);

  if (esp_now_init() != ESP_OK) {
    Serial.println("ESP-NOW init failed");
    return;
  }

  esp_now_register_send_cb(onDataSent);

  memcpy(peerInfo.peer_addr, receiverMAC, 6);
  peerInfo.channel = 0;
  peerInfo.encrypt = false;

  if (esp_now_add_peer(&peerInfo) != ESP_OK) {
    Serial.println("Failed to add peer");
    return;
  }

  myData.counter = 0;
}

void loop() {
  myData.counter++;
  esp_err_t result = esp_now_send(receiverMAC, (uint8_t *)&myData, sizeof(myData));

  Serial.print("Sending counter: ");
  Serial.println(myData.counter);

  delay(1000);
}

/*
Sending counter: 5
Send status: Fail
Sending counter: 6
Send status: Fail
Sending counter: 7
Send status: Fail
Sending counter: 8
Send status: Fail
Sending counter: 9
Send status: Fail
Sending counter: 10
Send status: Success
Sending counter: 11
Send status: Success
Sending counter: 12
Send status: Success
Sending counter: 13
Send status: Success
Sending counter: 14
Send status: Success
Sending counter: 15
Send status: Success
Sending counter: 16
Send status: Success
Sending counter: 17
Send status: Success
Sending counter: 18
Send status: Success
Sending counter: 19
Send status: Success
Sending counter: 20
Send status: Success
Sending counter: 21
Send status: Success
Sending counter: 22
Send status: Success
Sending counter: 23
Send status: Success
Sending counter: 24
Send status: Success
Sending counter: 25
Send status: Success
Sending counter: 26
Send status: Success
Sending counter: 27
Send status: Success
Sending counter: 28
Send status: Success
Sending counter: 29
Send status: Success
Sending counter: 30
Send status: Success
Sending counter: 31
Send status: Success
Sending counter: 32
Send status: Success
Sending counter: 33
Send status: Success
Sending counter: 34
Send status: Success
Sending counter: 35
Send status: Success
Sending counter: 36
Send status: Success
Sending counter: 37
Send status: Success
Sending counter: 38
Send status: Success
Sending counter: 39
Send status: Success
Sending counter: 40
Send status: Success
Sending counter: 41
Send status: Success
Sending counter: 42
Send status: Success
Sending counter: 43
Send status: Success
Sending counter: 44
Send status: Success
Sending counter: 45
Send status: Success
Sending counter: 46
Send status: Success
Sending counter: 47
Send status: Success
Sending counter: 48
Send status: Success
Sending counter: 49
Send status: Success
Sending counter: 50
Send status: Success
Sending counter: 51
Send status: Success
Sending counter: 52
Send status: Success
Sending counter: 53
Send status: Success
Sending counter: 54
Send status: Success
Sending counter: 55
Send status: Success
Sending counter: 56
Send status: Success
Sending counter: 57
Send status: Success
Sending counter: 58
Send status: Success
Sending counter: 59
Send status: Success
Sending counter: 60
Send status: Success
Sending counter: 61
Send status: Success
Sending counter: 62
Send status: Success
Sending counter: 63
Send status: Success
Sending counter: 64
Send status: Success
Sending counter: 65
Send status: Success
Sending counter: 66
Send status: Success
Sending counter: 67
Send status: Success
Sending counter: 68
Send status: Success
Sending counter: 69
Send status: Success
Sending counter: 70
Send status: Success
Sending counter: 71
Send status: Success
Sending counter: 72
Send status: Success
Sending counter: 73
Send status: Success
Sending counter: 74
Send status: Success
Sending counter: 75
Send status: Success
Sending counter: 76
Send status: Success
Sending counter: 77
Send status: Success
Sending counter: 78
Send status: Success
Sending counter: 79
Send status: Success
Sending counter: 80
Send status: Success
Sending counter: 81
Send status: Success
Sending counter: 82
Send status: Success
Sending counter: 83
Send status: Success
Sending counter: 84
Send status: Success
Sending counter: 85
Send status: Success
Sending counter: 86
Send status: Success
Sending counter: 87
Send status: Success
Sending counter: 88
Send status: Success
Sending counter: 89
Send status: Success
Sending counter: 90
Send status: Success
Sending counter: 91
Send status: Success
Sending counter: 92
Send status: Success
Sending counter: 93
Send status: Success
Sending counter: 94
Send status: Success
Sending counter: 95
Send status: Success
Sending counter: 96
Send status: Success
Sending counter: 97
Send status: Success
Sending counter: 98
Send status: Success
Sending counter: 99
Send status: Success
Sending counter: 100
Send status: Success
Sending counter: 101
Send status: Success
Sending counter: 102
Send status: Success
Sending counter: 103
Send status: Success
Sending counter: 104
Send status: Success
Sending counter: 105
Send status: Success
Sending counter: 106
Send status: Success
Sending counter: 107
Send status: Success
Sending counter: 108
Send status: Success
Sending counter: 109
Send status: Success
Sending counter: 110
Send status: Success
Sending counter: 111
Send status: Success
Sending counter: 112
Send status: Success
Sending counter: 113
Send status: Success
Sending counter: 114
Send status: Success
Sending counter: 115
Send status: Success
Sending counter: 116
Send status: Success
Sending counter: 117
Send status: Success
Sending counter: 118
Send status: Success
Sending counter: 119
Send status: Success
Sending counter: 120
Send status: Success
Sending counter: 121
Send status: Success
Sending counter: 122
Send status: Success
Sending counter: 123
Send status: Success
Sending counter: 124
Send status: Success
Sending counter: 125
Send status: Success
Sending counter: 126
Send status: Success
Sending counter: 127
Send status: Success
Sending counter: 128
Send status: Success
Sending counter: 129
Send status: Success
Sending counter: 130
Send status: Success
Sending counter: 131
Send status: Success
Sending counter: 132
Send status: Success
Sending counter: 133
Send status: Success
Sending counter: 134
Send status: Success
Sending counter: 135
Send status: Success
Sending counter: 136
Send status: Success
Sending counter: 137
Send status: Success
Sending counter: 138
Send status: Success
Sending counter: 139
Send status: Success
Sending counter: 140
Send status: Success
Sending counter: 141
Send status: Success
Sending counter: 142
Send status: Success
Sending counter: 143
Send status: Success
Sending counter: 144
Send status: Success
Sending counter: 145
Send status: Success
Sending counter: 146
Send status: Success
Sending counter: 147
Send status: Success
Sending counter: 148
Send status: Success
Sending counter: 149
Send status: Success
Sending counter: 150
Send status: Success
Sending counter: 151
Send status: Success
Sending counter: 152
Send status: Success
Sending counter: 153
Send status: Success
Sending counter: 154
Send status: Success
Sending counter: 155
Send status: Success
Sending counter: 156
Send status: Success
Sending counter: 157
Send status: Success
Sending counter: 158
Send status: Success
Sending counter: 159
Send status: Success
Sending counter: 160
Send status: Success
Sending counter: 161
Send status: Success
Sending counter: 162
Send status: Success
Sending counter: 163
Send status: Success
Sending counter: 164
Send status: Success
Sending counter: 165
Send status: Success
Sending counter: 166
Send status: Success
Sending counter: 167
Send status: Success
Sending counter: 168
Send status: Success
Sending counter: 169
Send status: Success
Sending counter: 170
Send status: Success
Sending counter: 171
Send status: Success
Sending counter: 172
Send status: Success
Sending counter: 173
Send status: Success
Sending counter: 174
Send status: Success
Sending counter: 175
Send status: Success
Sending counter: 176
Send status: Success
Sending counter: 177
Send status: Success
Sending counter: 178
Send status: Success
Sending counter: 179
Send status: Success
Sending counter: 180
Send status: Success
Sending counter: 181
Send status: Success
Sending counter: 182
Send status: Success
Sending counter: 183
Send status: Success
Sending counter: 184
Send status: Success
Sending counter: 185
Send status: Success
Sending counter: 186
Send status: Success
Sending counter: 187
Send status: Success
Sending counter: 188
Send status: Success
Sending counter: 189
Send status: Success
Sending counter: 190
Send status: Success
Sending counter: 191
Send status: Success
Sending counter: 192
Send status: Success
Sending counter: 193
Send status: Success
Sending counter: 194
Send status: Success
Sending counter: 195
Send status: Success
Sending counter: 196
Send status: Success
Sending counter: 197
Send status: Success
Sending counter: 198
Send status: Success
Sending counter: 199
Send status: Success
Sending counter: 200
Send status: Success
Sending counter: 201
Send status: Success
Sending counter: 202
Send status: Success
Sending counter: 203
Send status: Success
Sending counter: 204
Send status: Success
Sending counter: 205
Send status: Success
Sending counter: 206
Send status: Success
Sending counter: 207
Send status: Success
Sending counter: 208
Send status: Success
Sending counter: 209
Send status: Success
Sending counter: 210
Send status: Success
Sending counter: 211
Send status: Success
Sending counter: 212
Send status: Success
Sending counter: 213
Send status: Success
Sending counter: 214
Send status: Success
Sending counter: 215
Send status: Success
Sending counter: 216
Send status: Success
Sending counter: 217
Send status: Success
Sending counter: 218
Send status: Success
Sending counter: 219
Send status: Success
Sending counter: 220
Send status: Success
Sending counter: 221
Send status: Success
Sending counter: 222
Send status: Success
Sending counter: 223
Send status: Success
Sending counter: 224
Send status: Success
Sending counter: 225
Send status: Success
Sending counter: 226
Send status: Success
Sending counter: 227
Send status: Success
Sending counter: 228
Send status: Success
Sending counter: 229
Send status: Success
Sending counter: 230
Send status: Success
Sending counter: 231
Send status: Success
Sending counter: 232
Send status: Success
Sending counter: 233
Send status: Success
Sending counter: 234
Send status: Success
Sending counter: 235
Send status: Success
Sending counter: 236
Send status: Success
Sending counter: 237
Send status: Success
Sending counter: 238
Send status: Success
Sending counter: 239
Send status: Success
Sending counter: 240
Send status: Success
Sending counter: 241
Send status: Success
Sending counter: 242
Send status: Success
Sending counter: 243
Send status: Success
Sending counter: 244
Send status: Success
Sending counter: 245
Send status: Success
Sending counter: 246
Send status: Success
Sending counter: 247
Send status: Success
Sending counter: 248
Send status: Success
Sending counter: 249
Send status: Success
Sending counter: 250
Send status: Success
Sending counter: 251
Send status: Success
Sending counter: 252
Send status: Success
Sending counter: 253
Send status: Success
Sending counter: 254
Send status: Success
Sending counter: 255
Send status: Success
Sending counter: 256
Send status: Success
Sending counter: 257
Send status: Success
Sending counter: 258
Send status: Success
Sending counter: 259
Send status: Success
Sending counter: 260
Send status: Success
Sending counter: 261
Send status: Success
Sending counter: 262
Send status: Success
Sending counter: 263
Send status: Success
Sending counter: 264
Send status: Success
Sending counter: 265
Send status: Success
Sending counter: 266
Send status: Success
Sending counter: 267
Send status: Success
Sending counter: 268
Send status: Success
Sending counter: 269
Send status: Success
Sending counter: 270
Send status: Success
Sending counter: 271
Send status: Success
Sending counter: 272
Send status: Success
Sending counter: 273
Send status: Success
Sending counter: 274
Send status: Success
Sending counter: 275
Send status: Success
Sending counter: 276
Send status: Success
Sending counter: 277
Send status: Success
Sending counter: 278
Send status: Success
Sending counter: 279
Send status: Success
Sending counter: 280
Send status: Success
Sending counter: 281
Send status: Success
Sending counter: 282
Send status: Success
Sending counter: 283
Send status: Success
Sending counter: 284
Send status: Success
Sending counter: 285
Send status: Success
Sending counter: 286
Send status: Success
Sending counter: 287
Send status: Success
Sending counter: 288
Send status: Success
Sending counter: 289
Send status: Success
Sending counter: 290
Send status: Success
Sending counter: 291
Send status: Success
Sending counter: 292
Send status: Success
Sending counter: 293
Send status: Success
Sending counter: 294
Send status: Success
Sending counter: 295
Send status: Success
Sending counter: 296
Send status: Success
Sending counter: 297
Send status: Success
Sending counter: 298
Send status: Success
Sending counter: 299
Send status: Success
Sending counter: 300
Send status: Success
Sending counter: 301
Send status: Success
Sending counter: 302
Send status: Success
Sending counter: 303
Send status: Success
Sending counter: 304
Send status: Success
Sending counter: 305
Send status: Success
Sending counter: 306
Send status: Success
Sending counter: 307
Send status: Success
Sending counter: 308
Send status: Success
Sending counter: 309
Send status: Success
Sending counter: 310
Send status: Success
Sending counter: 311
Send status: Success
Sending counter: 312
Send status: Success
Sending counter: 313
Send status: Success
Sending counter: 314
Send status: Success
Sending counter: 315
Send status: Success
Sending counter: 316
Send status: Success
Sending counter: 317
Send status: Success
Sending counter: 318
Send status: Success
Sending counter: 319
Send status: Success
Sending counter: 320
Send status: Success
Sending counter: 321
Send status: Success
Sending counter: 322
Send status: Success
Sending counter: 323
Send status: Success
Sending counter: 324
Send status: Success
Sending counter: 325
Send status: Success
Sending counter: 326
Send status: Success
Sending counter: 327
Send status: Success
Sending counter: 328
Send status: Success
Sending counter: 329
Send status: Success
Sending counter: 330
Send status: Success
Sending counter: 331
Send status: Success
Sending counter: 332
Send status: Success
Sending counter: 333
Send status: Success
Sending counter: 334
Send status: Success
Sending counter: 335
Send status: Success
Sending counter: 336
Send status: Success
Sending counter: 337
Send status: Success
Sending counter: 338
Send status: Success
Sending counter: 339
Send status: Success
Sending counter: 340
Send status: Success
Sending counter: 341
Send status: Success
Sending counter: 342
Send status: Success
Sending counter: 343
Send status: Success
Sending counter: 344
Send status: Success
Sending counter: 345
Send status: Success
Sending counter: 346
Send status: Success
Sending counter: 347
Send status: Success
Sending counter: 348
Send status: Success
Sending counter: 349
Send status: Success
Sending counter: 350
Send status: Success
Sending counter: 351
Send status: Success
Sending counter: 352
Send status: Success
Sending counter: 353
Send status: Success
Sending counter: 354
Send status: Success
Sending counter: 355
Send status: Success
Sending counter: 356
Send status: Success
Sending counter: 357
Send status: Success
Sending counter: 358
Send status: Success
Sending counter: 359
Send status: Success
Sending counter: 360
Send status: Success
Sending counter: 361
Send status: Success
Sending counter: 362
Send status: Success
Sending counter: 363
Send status: Success
Sending counter: 364
Send status: Success
Sending counter: 365
Send status: Success
Sending counter: 366
Send status: Success
Sending counter: 367
Send status: Success
Sending counter: 368
Send status: Success
Sending counter: 369
Send status: Success
Sending counter: 370
Send status: Success
Sending counter: 371
Send status: Success
Sending counter: 372
Send status: Success
Sending counter: 373
Send status: Success
Sending counter: 374
Send status: Success
Sending counter: 375
Send status: Success
Sending counter: 376
Send status: Success
Sending counter: 377
Send status: Success
Sending counter: 378
Send status: Success
Sending counter: 379
Send status: Success
Sending counter: 380
Send status: Success
Sending counter: 381
Send status: Success
Sending counter: 382
Send status: Success
Sending counter: 383
Send status: Success
Sending counter: 384
Send status: Success
Sending counter: 385
Send status: Success
Sending counter: 386
Send status: Success
Sending counter: 387
Send status: Success
Sending counter: 388
Send status: Success
*/